PassionProject/Models/FoodPhoto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;
using System.ComponentModel.DataAnnotations;

namespace PassionProject.Models
{
    public class FoodPhoto
    {
            [Key]
             public int FoodPhotoID { get; set; }


            // Column to save the image location
            [StringLength(150), Display(Name = "Image Path")]
            public string ImagePath { get; set; }

            // Field for the caption
            
            public string PhotoCaption { get; set; }

            //Field for the details

            public string PhotoDetails { get; set; }

            
            //Key to link user to the photo
            public virtual User user { get; set; }
            
        
    }
}

PassionProject/Controllers/FoodPhotoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;
using PassionProject.Models.ViewModels;
using System.Diagnostics;

namespace PassionProject.Controllers
{
    public class FoodPhotoController : Controller
    {
        private FoodPhotoCMSContext db = new FoodPhotoCMSContext();
        // GET: FoodPhoto
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult List()
        {
            // Creates multiples of the foodphoto object 
            IEnumerable<FoodPhoto> foodphotos = db.FoodPhotos.ToList();
            return View(foodphotos);
        }

        public ActionResult Create()
        {
            //Creates multiple user objects and puts them into a list
            IEnumerable<User> usernames = db.Users.ToList();
                return View(usernames);
        }
        // This code mainly references Christine's project however Kento helped me with the image uploading feature
        // Here are the links to the tutorials used https://stackoverflow.com/questions/16255882/uploading-displaying-images-in-mvc-4
        // https://stackoverflow.com/questions/24625078/how-generate-a-unique-file-name-at-upload-files-in-webserver-mvc
        [HttpPost]
        public ActionResult Create(string PhotoCaption_New, string PhotoDetails_New, int UserUploader_New, FoodPhoto foodphoto, HttpPostedFileBase file)
        {
            if (file != null)
                {

                // Saving the image with a unique name
                var newImg = DateTime.Now.ToString("yyyymmddMMss") + System.IO.Path.GetExtension(file.FileName);

                //Save the actual root image file
                file.SaveAs(HttpContext.Server.MapPath("~/Images/") + newImg);

                foodphoto.ImagePath = newImg;

                string query = "insert into FoodPhotoes (ImagePath, PhotoCaption, PhotoDetails, User_UserID) values(@ImagePath, @caption, @details, @user)";
                SqlParameter[] myparams = {
                     new SqlParameter("@ImagePath", foodphoto.ImagePath),
                     new SqlParameter("@caption", PhotoCaption_New),
                     new SqlParameter("@details", PhotoDetails_New),
                     new SqlParameter("@user", UserUploader_New)

                };

                db.Database.ExecuteSqlCommand(query, myparams);
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }

        public ActionResult Edit(int? id)
        {
            // Edit action -> uses the foodphoto edit made to grab a single foodphoto object and multiple users to be displayed on the
            //edit view page
            FoodPhotoEdit foodphotoeditview = new FoodPhotoEdit();
            foodphotoeditview.users = db.Users.ToList();
            foodphotoeditview.foodphoto = db.FoodPhotos.Find(id);

            return View(foodphotoeditview);
        }
        [HttpPost]
        public ActionResult Edit(int? id, string PhotoCaption, string PhotoDetails, int Username, FoodPhoto foodphoto)
        {
            // checking to make the object we are editing exists
            if ((id== null) || (db.FoodPhotos.Find(id)== null))
            {
                return HttpNotFound();
            }

           // Query to update exisiting object and it's fields in the database
            string query = "update FoodPhotoes set PhotoCaption = @caption, PhotoDetails=@details, User_UserID=@user where foodphotoid=@id";
            SqlParameter[] myparams = {
                 new SqlParameter("@caption", PhotoCaption),
                 new SqlParameter("@details", PhotoDetails),
                 new SqlParameter("@user", Username),
                 new SqlParameter("@id",id)

            };

              db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }

        public ActionResult Delete(int id)
        {
           //query to delete an object from the database where the object matches the id passed through
            string query = "delete from FoodPhotoes where FoodPhotoID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));


            return RedirectToAction("List");
        }

        public ActionResult Show(int id)
        {

            // checking to make the object we want to show exists
            if ((id == null) || (db.FoodPhotos.Find(id) == null))
            {
                return HttpNotFound();
            }

            // query to display a single object from a database where object id matches passed id 
            string query = "select * from FoodPhotoes where FoodPhotoID=@id";
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            FoodPhoto newfoodphoto = db.FoodPhotos.SqlQuery(query, myparams).FirstOrDefault();

            return View(newfoodphoto);
        }
    }
}

PassionProject/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.SqlClient;
using System.Data.Entity;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PassionProject.Models;

namespace PassionProject.Controllers
{
    public class UserController : Controller
    {
        private FoodPhotoCMSContext db = new FoodPhotoCMSContext();
        // GET: User
        public ActionResult Index()
        {
            return View();
        }
   

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(string UserName_New, User user)
        {
            string query = "insert into Users(UserName)" + "values(@username)";
            SqlParameter[] myparams = {
                 new SqlParameter("@username", UserName_New)
            };
            db.Database.ExecuteSqlCommand(query, myparams);
            return RedirectToAction("List");
        }

    public ActionResult List()
        {
            string query = "select * from Users";
            IEnumerable<User> users = db.Users.SqlQuery(query);

            return View(users);
        }

    public ActionResult Delete(int id)
        {

            string query = "delete from FoodPhotoes where User_UserID=@id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

            query = "delete from Users where UserID = @id";
            db.Database.ExecuteSqlCommand(query, new SqlParameter("@id", id));

           


            return RedirectToAction("List");
        }

    public ActionResult Show(int? id)
        {

            // checking to make the object we want to show exists
            if ((id == null) || (db.Users.Find(id) == null))
            {
                return HttpNotFound();
            }

            // query to display a single object from a database where object id matches passed id 
            string query = "select * from Users where UserID=@id";
            SqlParameter[] myparams = new SqlParameter[1];
            myparams[0] = new SqlParameter("@id", id);

            User newuser = db.Users.SqlQuery(query, myparams).FirstOrDefault();

            return View(newuser);
        }

        /* couldn't get this to work so left it in to show what I tried but commented it out and
         * deleted the view so the files would still run
         * public ActionResult Edit(int? id)
        {
            return View();
        }

        [HttpPost]
        public ActionResult Edit(int id, string UserName, User user)
        {
            // checking to make the object we are editing exists
            if ((id == null) || (db.Users.Find(id) == null))
            {
                return HttpNotFound();
            }

            // Query to update exisiting object and it's fields in the database
            string query = "update Users set UserName=@username where userid=@id";
            SqlParameter[] myparams = {
                 new SqlParameter("@username", UserName),
                 new SqlParameter("@id",id)

            };

            db.Database.ExecuteSqlCommand(query, myparams);

            return RedirectToAction("List");
        }*/


    }
}

PassionProject/Views/FoodPhoto/Create.cshtml
@model IEnumerable<PassionProject.Models.User>
@{
    ViewBag.Title = "Add a new photo!";
}


    <div>
        <h2 class="pagetitle"> Add a photo</h2>
        <!--Kento helped me write this code-->
        @using (Html.BeginForm("Create/", "FoodPhoto", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="inprow">
                <label for="imgupload"> Upload your image: </label>
                <input id="ImgPath" title="Upload your image" type="file" name="file" />
            </div>
            <div class="inprow">
                <label class="inplabel">Caption</label><br />
                <input id="PhotoCaption_New" name="PhotoCaption_New" />
            </div>
            <div class="inprow">
                <label class="inplabel">Details</label><br />
                <textarea rows="4" cols="30" id="PhotoDetails_New" name="PhotoDetails_New">Recipe instructions and details...</textarea>
            </div>
            <div class="inprow">
                <label class="inplabel">Username: </label>
                <select id="UserUploader_New" name="UserUploader_New">
                    @foreach (var user in Model)
                    {
                        <option value="@user.UserID">@user.UserName</option>
                    }
                </select>
            </div>
            <div class="inprow">
                <input type="submit" value="Submit"/>
            </div>

        }
    
    </div>


PassionProject/Views/FoodPhoto/Edit.cshtml
@model PassionProject.Models.ViewModels.FoodPhotoEdit

@{
    ViewBag.Title = "Edit";
}

<h2 class="pagetitle">Edit</h2>


<form method="POST" action="/FoodPhoto/Edit/@Model.foodphoto.FoodPhotoID">
    <div id="showpage">

        <div class="displaySinglePhoto">
            <img src="/Images/@(Model.foodphoto.ImagePath)" />
        </div>
        <div class="inprow">
            <label class="inplabel">Caption</label>
            <input type="text" value="@Model.foodphoto.PhotoCaption" id="PhotoCaption" name="PhotoCaption" />
        </div>
        <div class="inprow">
            <label class="inplabel">Details</label><br />
                                                   <textarea rows="4" cols="30" id="PhotoDetails" name="PhotoDetails"> @Model.foodphoto.PhotoDetails</textarea>
        </div>
        <div class="inplable">Username</div>
        <select id="Username" name="Username">
            @foreach (var user in Model.users)
            {
                string current = "";
                if (user.UserID == Model.foodphoto.user.UserID)
                {
                    current = "selected";
                }

                <option value="@user.UserID" @current>@user.UserName</option>
            }
        </select>
        <div class="inprow">
            <input type="submit" value="Submit" />
        </div>
    </div>

</form>

PassionProject/Views/FoodPhoto/Index.cshtml
@model PassionProject.Models.FoodPhoto

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


  

PassionProject/Views/FoodPhoto/List.cshtml
@model IEnumerable<PassionProject.Models.FoodPhoto>
@{
    ViewBag.Title = "List";
    int colCounter = 0;
}

<div><img id="bannerimg" src="/Images/10mm-01.png" /></div>
<h2 class="pagetitle">10 Minute Meal Ideas!</h2>


<!--Used this tutorial to help use bootstrap grid within a foreach loop https://www.jerriepelser.com/blog/approaches-when-rendering-list-using-bootstrap-grid-system/ -->
<div class="container">
    @foreach (var foodphoto in Model)
    {
        if (colCounter != 0 && colCounter % 3 == 0)
        {
        @:</div>
        @:<div class="row">
        }
              <div class="col-md-4">
                  <div class="displayPhoto">
                      <img src="/Images/@(foodphoto.ImagePath)" />
                  </div>
                  <h2 class="caption">@Html.ActionLink(foodphoto.PhotoCaption,"Show/" + foodphoto.FoodPhotoID)</h2><br />
                  <span class="username">@foodphoto.user.UserName</span><br />  
                  <span class="edit">@Html.ActionLink("Edit", "Edit/" + foodphoto.FoodPhotoID) | </span>
                  <span class="delete">@Html.ActionLink("Delete", "Delete/" + foodphoto.FoodPhotoID)</span>

              </div>

        colCounter++;
    }

</div>


PassionProject/Views/FoodPhoto/Show.cshtml
@model PassionProject.Models.FoodPhoto

@{
    ViewBag.Title = "Show";
}

<h2 class="pagetitle">@Model.PhotoCaption</h2>
<h3 class="showauthor">@Html.ActionLink(Model.user.UserName,"Show/" + Model.user.UserID, "User")</h3>

<div id="showpage">
    <div class="displaySinglePhoto">
        <img src="/Images/@(Model.ImagePath)" />
    </div>
    <p>@Model.PhotoDetails</p>
    <span class="edit">@Html.ActionLink("Edit", "Edit/" + Model.FoodPhotoID) | </span>
    <span class="delete">@Html.ActionLink("Delete", "Delete/" + Model.FoodPhotoID)</span>
</div>


